// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CryptoChain struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Symbol    string `json:"symbol"`
	ImagePath string `json:"imagePath"`
	CreatedAt string `json:"createdAt"`
}

type Merchant struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Category     string        `json:"category"`
	Location     string        `json:"location"`
	Latitude     float64       `json:"latitude"`
	Longitude    float64       `json:"longitude"`
	CreatedAt    string        `json:"createdAt"`
	VerifiedAt   *string       `json:"verifiedAt,omitempty"`
	CryptoChains []CryptoChain `json:"cryptoChains"`
}

type Query struct {
}
